import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { test, type Page } from '@playwright/test';

/**
 * Every button, link and form control, and whether anything ever clicks it.
 *
 * ---------------------------------------------------------------------------
 * REPORTED, NOT ENFORCED, AND THAT IS DELIBERATE.
 * ---------------------------------------------------------------------------
 * A control nothing clicks is INFORMATION. Some of them should be clicked and
 * are not -- that is a coverage hole worth closing. Others are legitimately
 * unreachable in a fixture: "Reckon with it" only appears on an unanswered
 * miss, "Claim" only once something has been granted. Failing on those would
 * teach everyone to add the control to an allow-list, which is how a useful
 * report becomes a rubber stamp.
 *
 * The inventory is taken live, because a control that only renders in one
 * state cannot be found by reading the source. Whether it is clicked is read
 * from the source, because no reporter can tell you that across five projects
 * and three workers.
 * ---------------------------------------------------------------------------
 */
test.skip(
  !process.env.PACT_E2E_IDENTIFIER || !process.env.PACT_E2E_PASSWORD,
  'Set PACT_E2E_IDENTIFIER and PACT_E2E_PASSWORD to run.',
);

const SURFACES = [
  '/dashboard',
  '/tomorrow',
  '/week',
  '/progress',
  '/postponements',
  '/settings',
  '/stakes',
  '/study',
  '/study/curriculum',
  '/study/phases',
  '/study/review',
];

interface Control {
  role: string;
  name: string;
}

async function inventory(page: Page): Promise<Control[]> {
  return page.evaluate(() => {
    const out: { role: string; name: string }[] = [];
    const seen = new Set<string>();

    const label = (element: Element): string =>
      (
        element.getAttribute('aria-label') ??
        (element as HTMLInputElement).placeholder ??
        element.textContent ??
        ''
      )
        .trim()
        .replace(/\s+/g, ' ')
        .slice(0, 60);

    for (const element of document.querySelectorAll(
      'main button, main a[href], main input:not([type="hidden"]), main select, main textarea',
    )) {
      if ((element as HTMLElement).offsetParent === null) continue;

      const role =
        element.tagName === 'A'
          ? 'link'
          : element.tagName === 'BUTTON'
            ? 'button'
            : element.tagName.toLowerCase();
      const name = label(element);
      const key = `${role}:${name}`;
      if (name && !seen.has(key)) {
        seen.add(key);
        out.push({ role, name });
      }
    }

    return out;
  });
}

/** Accessible names that some spec actually clicks or fills. */
function namesExercised(): Set<string> {
  const dir = join(process.cwd(), 'e2e');
  const names = new Set<string>();

  const collect = (path: string): void => {
    for (const entry of readdirSync(path, { withFileTypes: true })) {
      const full = join(path, entry.name);
      if (entry.isDirectory()) {
        collect(full);
        continue;
      }
      if (!/\.(spec|setup)\.ts$/.test(entry.name)) continue;

      const code = readFileSync(full, 'utf8');

      /**
       * `getByRole('button', { name: 'Complete' })`, `getByLabel('Password')`
       * and `locator('input[name="title"]')` -- the three ways this suite
       * addresses a control. A name appearing anywhere in the suite counts:
       * proving WHICH spec clicked which instance is not worth the machinery.
       */
      for (const match of code.matchAll(/name:\s*'([^']+)'/g)) names.add(match[1]!.toLowerCase());
      for (const match of code.matchAll(/getByLabel\('([^']+)'/g))
        names.add(match[1]!.toLowerCase());
      for (const match of code.matchAll(/getByText\(\s*'([^']+)'/g))
        names.add(match[1]!.toLowerCase());
      for (const match of code.matchAll(/input\[name="([^"]+)"\]/g))
        names.add(match[1]!.toLowerCase());
    }
  };

  collect(dir);

  return names;
}

test('takes an inventory of every control, and reports what nothing clicks', async ({ page }) => {
  /**
   * Eleven surfaces in one test, each a server render against an M0 cluster.
   * The default thirty seconds is a budget for one page, not for a tour, and
   * exceeding it reports as "waitForLoadState timed out" -- which reads as a
   * hanging page rather than a test doing eleven times more work than the
   * timeout was set for.
   */
  test.setTimeout(180_000);

  const exercised = namesExercised();
  const report: string[] = [
    '<!-- Generated by `npx playwright test inventory`. Do not edit by hand. -->',
    '',
    '# Interactive inventory',
    '',
    'Every button, link and form control rendered on each surface, and whether',
    'any spec addresses it by name. Unexercised is not the same as broken: some',
    'controls only appear in a state the fixture does not reach.',
    '',
  ];

  let total = 0;
  let untouched = 0;

  for (const path of SURFACES) {
    await page.goto(path);
    await page.waitForLoadState('networkidle');

    const controls = await inventory(page);
    report.push(`## ${path}`, '');

    if (controls.length === 0) {
      report.push('_No interactive controls rendered in this fixture state._', '');
      continue;
    }

    for (const control of controls) {
      total += 1;
      const hit = exercised.has(control.name.toLowerCase());
      if (!hit) untouched += 1;
      report.push(`- ${hit ? 'exercised' : 'NOT EXERCISED'} — ${control.role}: ${control.name}`);
    }
    report.push('');
  }

  report.push('## Summary', '', `${total} controls, ${untouched} never addressed by any spec.`, '');

  const path = join('docs/private', 'INVENTORY.md');
  writeFileSync(path, report.join('\n'));

  console.log(`\n  Interactive inventory: ${path} (${untouched}/${total} unexercised)\n`);
});
