import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Page } from '@playwright/test';

/**
 * The walkthrough's camera, and the index it writes.
 *
 * ---------------------------------------------------------------------------
 * THE OUTPUT IS THE MANUAL'S SCREENSHOTS SECTION, GENERATED.
 * ---------------------------------------------------------------------------
 * `docs/private/OPERATING.md` ends with a Screenshots placeholder. Pasting
 * images in by hand produces a section that is accurate on the day it is
 * written and misleading every month after, and a second run appends rather
 * than refreshes.
 *
 * So the run writes the images AND the markdown that references them, keyed on
 * the manual's own section numbers. Re-running overwrites both.
 * ---------------------------------------------------------------------------
 */
export const SCREENSHOT_DIR = 'docs/private/screenshots';

/** The two widths the responsive pass already commits to. */
export const WIDTHS = [
  { name: 'phone', width: 390, height: 844 },
  { name: 'desktop', width: 1440, height: 900 },
] as const;

export interface Shot {
  /** The manual's heading, verbatim: "2.2 Starting a block". */
  section: string;
  /** What this particular frame shows, when a section has several. */
  caption: string;
  files: { width: string; path: string }[];
}

const shots: Shot[] = [];

export function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** `2-2-starting-a-block--the-timer.phone.png` */
export function fileName(section: string, caption: string, width: string): string {
  return `${slug(section)}--${slug(caption)}.${width}.png`;
}

/**
 * Captures the current page at both widths.
 *
 * The viewport is restored afterwards, because a step that silently left the
 * page at 1440 would make every later assertion about a phone layout a lie.
 */
export async function capture(page: Page, section: string, caption: string): Promise<void> {
  mkdirSync(SCREENSHOT_DIR, { recursive: true });

  const original = page.viewportSize();
  const files: Shot['files'] = [];

  for (const size of WIDTHS) {
    await page.setViewportSize({ width: size.width, height: size.height });
    // Layout settles after a resize; a frame taken mid-reflow looks like a
    // rendering bug in the manual rather than a timing artefact in the run.
    await page.waitForTimeout(150);

    const path = join(SCREENSHOT_DIR, fileName(section, caption, size.name));
    await page.screenshot({ path, fullPage: true });
    files.push({ width: size.name, path });
  }

  if (original) await page.setViewportSize(original);

  shots.push({ section, caption, files });
}

/** Everything captured so far, for the index writer. */
export function captured(): readonly Shot[] {
  return shots;
}

/**
 * Writes the markdown the manual includes.
 *
 * A separate file rather than an edit to OPERATING.md: the manual is prose
 * somebody maintains, and a generator that rewrites part of a hand-written
 * document eventually eats a paragraph. The manual references this; the run
 * replaces it wholesale.
 */
export function writeIndex(): string {
  const bySection = new Map<string, Shot[]>();
  for (const shot of shots) {
    bySection.set(shot.section, [...(bySection.get(shot.section) ?? []), shot]);
  }

  const lines: string[] = [
    '<!-- Generated by `npx playwright test walkthrough`. Do not edit by hand. -->',
    '',
    '# Screenshots',
    '',
    `Captured at ${WIDTHS.map((size) => `${size.width}px`).join(' and ')}, in the order a`,
    'person meets the application. Section numbers match OPERATING.md.',
    '',
  ];

  for (const [section, entries] of bySection) {
    lines.push(`## ${section}`, '');
    for (const shot of entries) {
      lines.push(`**${shot.caption}**`, '');
      for (const file of shot.files) {
        // Relative to the manual, which sits one directory above the images.
        const href = file.path.replace('docs/private/', '');
        lines.push(`- ${file.width}: ![${shot.caption} (${file.width})](${href})`);
      }
      lines.push('');
    }
  }

  const path = join('docs/private', 'SCREENSHOTS.md');
  writeFileSync(path, lines.join('\n'));

  return path;
}
